### ISSUE TITLE
Update to Laravel 5

### ISSUE THREAD

**Issue by pmller** [fians/larapack#2]
I've tried this package recently and as someone who understands nothing of composer but want's to get into toying with Laravel a bit to see if it is for me before learning composer (I guess its needed to work in the Laravel world on a day to day basis) I was wondering if there is a chance for the package to updated to Laravel 5.
Even though I guess the mainstream is not to use Laravel this way I personally would really appreciate this as a way to get more comfortable with the framework.

**Comment by fians** [comment]
Updated :wink:
